services:
  _defaults:
    autowire: true

  Bookboon\JsonLDClient\Serializer\JsonLDEncoder:
    tags:
      - serializer.encoder

  Bookboon\JsonLDClient\Serializer\NullableDateTimeNormalizer:
    tags:
      - serializer.normalizer

  Bookboon\JsonLDClient\Serializer\JsonLDNormalizer:
    tags:
      - serializer.normalizer

  GuzzleHttp\ClientInterface:
    class: GuzzleHttp\Client

  Bookboon\JsonLDClient\Client\JsonLDClient: ~
