services:
  Bookboon\JsonLDClient\Serializer\JsonLDEncoder:
    tags:
      - serializer.encoder

  Bookboon\JsonLDClient\Serializer\NullableDateTimeNormalizer:
    arguments:
      - '@serializer.normalizer.datetime'
    tags:
      - serializer.normalizer

  Bookboon\JsonLDClient\Serializer\StdClassNormalizer:
    tags:
      - serializer.normalizer

  jsonldclient.handlerstack:
    class: GuzzleHttp\HandlerStack
    factory: ['Bookboon\JsonLDClient\Client\GuzzleClientFactory', 'createStack']

  jsonldclient.client:
    class: GuzzleHttp\ClientInterface
    factory: ['Bookboon\JsonLDClient\Client\GuzzleClientFactory', 'create']
    arguments: ['@request_stack', '@jsonldclient.handlerstack']

  jsonldclient.property_extractor:
    class: Symfony\Component\PropertyInfo\PropertyInfoExtractor
    arguments:
      - ['@property_info.php_doc_extractor', '@property_info.reflection_extractor']
      - ['@property_info.php_doc_extractor', '@property_info.reflection_extractor']
      - []
      - []
      - []

  jsonldclient.property_accessor:
    alias: 'property_accessor'
    public: true

  jsonldclient.object_normalizer:
    class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
    arguments:
      - null
      - null
      - '@jsonldclient.property_accessor'
      - '@jsonldclient.property_extractor'
      - null
      - null
      - []
    calls:
      - [setSerializer, ['@serializer']]

  Bookboon\JsonLDClient\Serializer\JsonLDNormalizer:
    arguments:
      - '@jsonldclient.object_normalizer'
      - '@Bookboon\JsonLDClient\Mapping\MappingCollection'
    tags:
      - serializer.normalizer

  Bookboon\JsonLDClient\Serializer\JsonLDMapNormalizer:
    arguments:
      - '@jsonldclient.object_normalizer'
      - '@Bookboon\JsonLDClient\Mapping\MappingCollection'
    tags:
      - serializer.normalizer

  Bookboon\JsonLDClient\Client\JsonLDClient:
    arguments:
      - '@jsonldclient.client'
      - '@serializer'
      - '@Bookboon\JsonLDClient\Mapping\MappingCollection'
      - '@?jsonldclient.cache'
