services:
  Bookboon\JsonLDClient\Serializer\JsonLDEncoder:
    tags:
      - serializer.encoder

  Bookboon\JsonLDClient\Serializer\NullableDateTimeNormalizer:
    tags:
      - serializer.normalizer

  jsonldclient.client:
    class: GuzzleHttp\Client

  jsonldclient.object_normalizer:
    class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
    arguments:
      - null
      - null
      - '@property_accessor'
      - '@property_info.php_doc_extractor'
      - null
      - null
      - []
    calls:
      - [setSerializer, ['@serializer']]

  Bookboon\JsonLDClient\Serializer\JsonLDNormalizer:
    arguments:
      - '@jsonldclient.object_normalizer'
      - '@Bookboon\JsonLDClient\Mapping\MappingCollection'
    tags:
      - serializer.normalizer

  Bookboon\JsonLDClient\Client\JsonLDClient:
    arguments:
      - '@jsonldclient.client'
      - '@serializer'
      - '@Bookboon\JsonLDClient\Mapping\MappingCollection'
      - '@?jsonldclient.cache'
