language: php

php:
  - 7.4
  - 8.0

env:
  global:
    secure: k/lbDsHyTDJiGTApQVwsaLlc3/QhnRw2QNuQawjq0+kNtZ8o5cpJQB2qZ3wmdqRBZ6xPpZgQ7JjCnMCOliaKVhBEHK5cCapIyDd2MfEvMUTjqnx6lXTJ4h5rngcIsSh7vQm3EZWQwLVBnwxM5nWK9JevlWA1Pcryst1D09D/OHscURJsCF55OQjc6T8S3QGEI+MRrhFVBKazZSIEjfv3ce6SJnVcA2TtBSFBhME3wQJPm5ur2LAFwDztBIadPJjNSHN2e6AuvolBotKwJC18h8Bu78WUONVK5/NUFqc7zbq1EQybIrvpqDbQkEaViTAHvPWP1i6bQhQdltqnS9jhhDn0x2UEblP01wAeti0UXa0kbjSecgJLbgdaUCq8kAnkhQrtsDBikbmGl7YIcZJe6m6NoFxf2mTcyU4dzO3bj3ClIFVvEww0jgamZZKSdZLhlRePwVhMS9wQPwMwqwv9ucoy3RrYD1CfKMccnznLIWY143VKMDnwA8fEPXVJNcKqL4y6dxKsGzPeIRKYUktYipMzRYDQFi6Xax8alm4smJSJavHk4GzP4FstISnvhSRkpZyZmoo4EzMltptlmk2noR41990FtfN2+pZRqsy1JOs1Z57nc2ak+LNMid1fBq4XclbS0/k88L1WIUb0eqhpx4ABNFblD9dAJcjAqR3MEg0=

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: vendor/bin/phpunit -c . --coverage-clover build/logs/clover.xml
    - name: "phpstan"
      script: vendor/bin/phpstan analyse -c phpstan.neon
    - name: "psalm"
      script: vendor/bin/psalm

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - composer install

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
